const {
  findOrCreateSession,
  getConversationHistory,
  saveUserMessage,
  saveAssistantMessage
} = require('../services/sessionService');
const { generateWhatsappReply } = require('../services/openaiService');
const { sendWhatsAppMessage } = require('../services/fonnteService');
const { buildRecommendationContextForLLM } = require('../services/propertyRecommendationService');

function readIncomingPayload(body = {}) {
  const sender = body.sender || body.from || body.phone || body.target || body.number || '';
  const message = body.message || body.text || body.body || '';
  const name = body.name || body.pushName || 'WhatsApp Customer';
  return {
    sender: String(sender).trim(),
    name: String(name).trim(),
    message: String(message).trim()
  };
}

exports.handleWebhook = async (req, res) => {
  const incoming = readIncomingPayload(req.body);

  if (!incoming.sender || !incoming.message) {
    return res.status(400).json({ success: false, message: 'Webhook payload must include sender and message.' });
  }

  try {
    const session = await findOrCreateSession(incoming.name, incoming.sender, 'whatsapp_fonnte');
    await saveUserMessage(session.id, incoming.message, 'whatsapp');

    const history = await getConversationHistory(session.id, 12);
    const recommendationContext = await buildRecommendationContextForLLM(incoming.message, history);

    // IMPORTANT: every WhatsApp chatbot reply is generated by OpenAI using backend property catalog context.
    const reply = await generateWhatsappReply(
      session,
      history,
      incoming.message,
      recommendationContext.contextText
    );

    await saveAssistantMessage(session.id, reply, 'whatsapp', {
      source: 'openai',
      exactMatches: recommendationContext.exactMatches.length,
      alternatives: recommendationContext.alternatives.length,
      filters: recommendationContext.filters
    });

    const fonnteResult = await sendWhatsAppMessage(incoming.sender, reply);

    return res.json({
      success: true,
      message: 'Webhook processed successfully.',
      target: fonnteResult.target,
      source: 'openai'
    });
  } catch (error) {
    console.error('Fonnte webhook processing failed:', error);
    return res.status(500).json({
      success: false,
      message: error.message || 'Failed to process Fonnte webhook through OpenAI.'
    });
  }
};
